[theme]
base = "light"
primaryColor = "#6699C2"
backgroundColor = "#F3F8FC"
secondaryBackgroundColor = "#E7F1F8"
textColor = "#102A43"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
